Headless Argument
nateshmbhat/webbot pull request #54
Opened 2020-10-16 01:16 UTC by GitPushPullLegs

I had to tweak it like this to get headless to work for me, figured you might like it too.

2020-12-15 17:36 UTC, GitPushPullLegs commented
@nateshmbhat just a reminder of this PR. If you'd like to me to tweak it please let me know.

2020-12-15 23:21 UTC, nateshmbhat commented
See this answer : https://stackoverflow.com/a/46929945/6665568

That argument is not needed.

2020-12-16 04:43 UTC, nateshmbhat commented
What u can do is, not remove that headless parameter line.

2020-12-16 04:43 UTC, nateshmbhat requested changes

2020-12-16 04:43 UTC, nateshmbhat commented on webbot/webbot.py
> -            options.headless = True
Don't remove this line. Let it be.

2020-12-18 04:49 UTC, GitPushPullLegs commented on webbot/webbot.py
> -            options.headless = True
Okay, I've added it back in.

2020-12-18 04:55 UTC, nateshmbhat approved these changes

2020-12-18 04:55 UTC, merged